--- #YAML:1.0
name:               Proc-JobQueue
version:            0.4
abstract:           Jobqueue with dependency graph
author:
    - David Muir Sharnoff <muir@idiom.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    aliased:              0
    Callback:             0
    Eval::LineNumbers:    0
    File::Slurp:          0
    File::Slurp::Remote::BrokenDNS:  0
    File::Temp:           0
    Hash::Util:           0
    Object::Dependency:   0
    Proc::Background:     0
    RPC::ToWorker:        0
    Scalar::Util:         0
    Tie::Function::Examples:  0
    Time::HiRes:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
